# Generated by Django 4.2.4 on 2023-08-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kotalicious', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_price', models.IntegerField()),
                ('product_ingredients', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_email',
            field=models.EmailField(max_length=254),
        ),
    ]
