# Generated by Django 4.2.4 on 2023-08-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kotalicious', '0002_product_alter_customer_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.CharField(default='/bae.jpg', max_length=40),
            preserve_default=False,
        ),
    ]
