# Generated by Django 4.2.4 on 2023-09-02 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kotalicious', '0002_customuser_profile_picture_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
    ]
