# Generated by Django 4.2.4 on 2023-08-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kotalicious', '0003_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_username',
            field=models.CharField(max_length=30),
            preserve_default=False,
        ),
    ]
